services:
  event_page:
    container_name: event_page_container
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  discord_bot:
    container_name: discord_bot_container
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - discord_db
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - test_db:/var/lib/mysql

volumes:
  test_db:
