services:
  discord_bot:
    container_name: discord_bot_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/
    command: sleep infinity
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - discord_bot_db_data_dev:/var/lib/mysql

volumes:
  discord_bot_db_data_dev:
