services:
  discord_bot:
    container_name: discord_bot_container
    ports:
      - "4000:4000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/
    command: sleep infinity
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - discord_bot_db_data_dev:/var/lib/mysql

volumes:
  discord_bot_db_data_dev:
